#!/usr/bin/env bash
# To infinity and beyond indefinitely
# With a sleep 2 in between each iteration
# I am invincible!!! when receiving a SIGTERM signal
echo $$ > /var/run/myscript.pid
trap "echo 'I hate the kill command'; sudo rm /var/run/myscript.pid; exit" 15
trap "echo 'Y U no love me?!'" 2
trap "sudo rm /var/run/myscript.pid; exit" 3
while true
do
    echo "To infinity and beyond"
    sleep 2
done
